### ISSUE TITLE
Index out of range error with newtonsoft

### ISSUE THREAD

**Issue by andrew74b** [nohwnd/Profiler#63] opened 2022-12-02 20:01 UTC
When I create my own converters inherited from Newtonsoft I get an error:
```
Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
```
I get the same error message when creating my own converters inheriting from 
- Newtonsoft.Json.JsonConverter[String]
- Newtonsoft.Json.Converters.IsoDateTimeConverter
- Newtonsoft.Json.JsonConverter[MongoDB.Bson.ObjectId]

Running my code works fine standalone, but when I try and profile it, I get the error.  Below is a stripped down and testable version of what I am running into, thanks!

```
Trace-Script {
  class DateTimeConverter : Newtonsoft.Json.Converters.IsoDateTimeConverter {
      [void] WriteJson([Newtonsoft.Json.JsonWriter]$writer, [Object]$value, [Newtonsoft.Json.JsonSerializer]$serializer) {
          $writer.WriteStartObject()
          $writer.WritePropertyName("`$date")
          $writer.WriteValue($value)
          $writer.WriteEndObject()
      }
  }
  [DateTimeConverter]::new()
}
```

**Comment by nohwnd** [comment] 2023-01-18 17:55
I actually have no idea why. I can see that the exception comes from the constructor you call, but it only happens in the context Trace-Script. 

```powershell
Trace-Script {
    class DateTimeConverter : Newtonsoft.Json.Converters.IsoDateTimeConverter {

        
        [void] WriteJson([Newtonsoft.Json.JsonWriter]$writer, [Object]$value, [Newtonsoft.Json.JsonSerializer]$serializer) {
            $writer.WriteStartObject()
            $writer.WritePropertyName("`$date")
            $writer.WriteValue($value)
            $writer.WriteEndObject()
        
        }
    }

    try { ([DateTimeConverter]::new()) } catch  { write-host $_.Exception }
}
```
```
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Text.StringBuilder.Insert(Int32 index, String value)
   at System.Management.Automation.Language.PositionUtilities.BriefMessage(IScriptPosition position)
   at System.Management.Automation.ScriptDebugger.TraceLine(IScriptExtent extent)
   at System.Management.Automation.ScriptDebugger.OnSequencePointHit(FunctionContext functionContext)
   at System.Management.Automation.ScriptDebugger.EnterScriptFunction(FunctionContext functionContext)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.ScriptBlock.InvokeWithPipeImpl(ScriptBlockClauseToInvoke clauseToInvoke, Boolean createLocalScope, Dictionary`2 functionsToDefine, List`1 variablesToDefine, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Object[] args)
   at System.Management.Automation.ScriptBlock.InvokeWithPipe(Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Boolean propagateAllExceptionsToTop, List`1 variablesToDefine, Dictionary`2 functionsToDefine, Object[] args)
   at System.Management.Automation.ScriptBlock.InvokeAsMemberFunction(Object instance, Object[] args)
   at System.Management.Automation.Internal.ScriptBlockMemberMethodWrapper.InvokeHelper(Object instance, Object sessionStateInternal, Object[] args)
   at CallSite.Target(Closure , CallSite , Type )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at System.Management.Automation.Interpreter.DynamicInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
Run finished after 00:00:00.0148005.
```

**Comment by fflaten** [comment] 2023-03-12 12:18
This is caused by https://github.com/PowerShell/PowerShell/issues/16874
Workaround: Add a default constructor in the class, ex `DateTimeConverter() { }`.

**Comment by nohwnd** [comment] 2023-05-10 19:50
Thanks for the links Frode, closing because this is not our bug.

**Closed by nohwnd** 2023-05-10 19:50 UTC
